USE i9vfjwzauoyk34wb;

CREATE TABLE unidades (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(35) NOT NULL,
cidade VARCHAR(35) NOT NULL,
uf VARCHAR(2) NOT NULL,
active BOOLEAN NOT NULL
);

CREATE TABLE funcionarios (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(50) NOT NULL,
cpf VARCHAR(9) NOT NULL UNIQUE,
cidade VARCHAR(35) NOT NULL,
uf VARCHAR(2) NOT NULL,
telefone VARCHAR(10),
celular VARCHAR(11) NOT NULL,
cep VARCHAR(8) NOT NULL,
endereco VARCHAR(100) NOT NULL,
complemento VARCHAR(20),
id_unidade INT NOT NULL,
area VARCHAR(20) NOT NULL,
cargo VARCHAR(20) NOT NULL,
salario DOUBLE NOT NULL,
active BOOLEAN NOT NULL,

FOREIGN KEY (id_unidade) REFERENCES unidades(id)
);

CREATE TABLE credenciais (
id_funcionario INT PRIMARY KEY,
login VARCHAR(20) NOT NULL,
senha VARCHAR(20) NOT NULL,
cod_acesso INT NOT NULL,

FOREIGN KEY (id_funcionario) REFERENCES funcionarios(id)
);

